# Generated by Django 5.0 on 2024-01-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='address',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
